version: '3.3'
services:
  prometheus:
    image: prom:local
    ports:
      - '9090:9090'

  node_exporter:
    image: prom/node-exporter

  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
